# Generated by Django 4.0.6 on 2024-04-24 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='localizacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='festivais.localizacao'),
        ),
        migrations.RemoveField(
            model_name='festival',
            name='banda',
        ),
        migrations.AddField(
            model_name='festival',
            name='banda',
            field=models.ManyToManyField(to='festivais.banda'),
        ),
    ]
