# Generated by Django 4.0.6 on 2024-05-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0002_alter_album_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos_bandas/'),
        ),
    ]
